package com.policemanagement.com.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AreaZoneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaZoneAllPropertiesEquals(AreaZone expected, AreaZone actual) {
        assertAreaZoneAutoGeneratedPropertiesEquals(expected, actual);
        assertAreaZoneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaZoneAllUpdatablePropertiesEquals(AreaZone expected, AreaZone actual) {
        assertAreaZoneUpdatableFieldsEquals(expected, actual);
        assertAreaZoneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaZoneAutoGeneratedPropertiesEquals(AreaZone expected, AreaZone actual) {
        assertThat(actual)
            .as("Verify AreaZone auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaZoneUpdatableFieldsEquals(AreaZone expected, AreaZone actual) {
        assertThat(actual)
            .as("Verify AreaZone relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getHamletName()).as("check hamletName").isEqualTo(expected.getHamletName()))
            .satisfies(a -> assertThat(a.getOfficerInCharge()).as("check officerInCharge").isEqualTo(expected.getOfficerInCharge()))
            .satisfies(a -> assertThat(a.getOfficerPhone()).as("check officerPhone").isEqualTo(expected.getOfficerPhone()))
            .satisfies(a -> assertThat(a.getPopulationCount()).as("check populationCount").isEqualTo(expected.getPopulationCount()))
            .satisfies(a -> assertThat(a.getHouseholdCount()).as("check householdCount").isEqualTo(expected.getHouseholdCount()))
            .satisfies(a -> assertThat(a.getBoundaryGeoJson()).as("check boundaryGeoJson").isEqualTo(expected.getBoundaryGeoJson()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaZoneUpdatableRelationshipsEquals(AreaZone expected, AreaZone actual) {
        // empty method
    }
}
