package com.policemanagement.com.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentRecordAllPropertiesEquals(DocumentRecord expected, DocumentRecord actual) {
        assertDocumentRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentRecordAllUpdatablePropertiesEquals(DocumentRecord expected, DocumentRecord actual) {
        assertDocumentRecordUpdatableFieldsEquals(expected, actual);
        assertDocumentRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentRecordAutoGeneratedPropertiesEquals(DocumentRecord expected, DocumentRecord actual) {
        assertThat(actual)
            .as("Verify DocumentRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentRecordUpdatableFieldsEquals(DocumentRecord expected, DocumentRecord actual) {
        assertThat(actual)
            .as("Verify DocumentRecord relevant properties")
            .satisfies(a -> assertThat(a.getDocName()).as("check docName").isEqualTo(expected.getDocName()))
            .satisfies(a -> assertThat(a.getDocType()).as("check docType").isEqualTo(expected.getDocType()))
            .satisfies(a -> assertThat(a.getHouseholdName()).as("check householdName").isEqualTo(expected.getHouseholdName()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getExpiryDate()).as("check expiryDate").isEqualTo(expected.getExpiryDate()))
            .satisfies(a -> assertThat(a.getOfficer()).as("check officer").isEqualTo(expected.getOfficer()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getReminderSent()).as("check reminderSent").isEqualTo(expected.getReminderSent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentRecordUpdatableRelationshipsEquals(DocumentRecord expected, DocumentRecord actual) {
        // empty method
    }
}
