package com.policemanagement.com.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HouseholdAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHouseholdAllPropertiesEquals(Household expected, Household actual) {
        assertHouseholdAutoGeneratedPropertiesEquals(expected, actual);
        assertHouseholdAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHouseholdAllUpdatablePropertiesEquals(Household expected, Household actual) {
        assertHouseholdUpdatableFieldsEquals(expected, actual);
        assertHouseholdUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHouseholdAutoGeneratedPropertiesEquals(Household expected, Household actual) {
        assertThat(actual)
            .as("Verify Household auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHouseholdUpdatableFieldsEquals(Household expected, Household actual) {
        assertThat(actual)
            .as("Verify Household relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getHouseNumber()).as("check houseNumber").isEqualTo(expected.getHouseNumber()))
            .satisfies(a -> assertThat(a.getStreet()).as("check street").isEqualTo(expected.getStreet()))
            .satisfies(a -> assertThat(a.getHamlet()).as("check hamlet").isEqualTo(expected.getHamlet()))
            .satisfies(a -> assertThat(a.getNeighborhoodGroup()).as("check neighborhoodGroup").isEqualTo(expected.getNeighborhoodGroup()))
            .satisfies(a -> assertThat(a.getAlley()).as("check alley").isEqualTo(expected.getAlley()))
            .satisfies(a -> assertThat(a.getOwnerName()).as("check ownerName").isEqualTo(expected.getOwnerName()))
            .satisfies(a -> assertThat(a.getOwnerPhone()).as("check ownerPhone").isEqualTo(expected.getOwnerPhone()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getBusinessName()).as("check businessName").isEqualTo(expected.getBusinessName()))
            .satisfies(a -> assertThat(a.getBusinessCategory()).as("check businessCategory").isEqualTo(expected.getBusinessCategory()))
            .satisfies(a -> assertThat(a.getResidentsCount()).as("check residentsCount").isEqualTo(expected.getResidentsCount()))
            .satisfies(a -> assertThat(a.getMaleCount()).as("check maleCount").isEqualTo(expected.getMaleCount()))
            .satisfies(a -> assertThat(a.getFemaleCount()).as("check femaleCount").isEqualTo(expected.getFemaleCount()))
            .satisfies(a -> assertThat(a.getUnder18Count()).as("check under18Count").isEqualTo(expected.getUnder18Count()))
            .satisfies(a -> assertThat(a.getAbove18Count()).as("check above18Count").isEqualTo(expected.getAbove18Count()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getWarningMessage()).as("check warningMessage").isEqualTo(expected.getWarningMessage()))
            .satisfies(a -> assertThat(a.getLicenseExpiry()).as("check licenseExpiry").isEqualTo(expected.getLicenseExpiry()))
            .satisfies(a -> assertThat(a.getLicenseType()).as("check licenseType").isEqualTo(expected.getLicenseType()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getLastCheckedDate()).as("check lastCheckedDate").isEqualTo(expected.getLastCheckedDate()))
            .satisfies(a -> assertThat(a.getOfficerInCharge()).as("check officerInCharge").isEqualTo(expected.getOfficerInCharge()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHouseholdUpdatableRelationshipsEquals(Household expected, Household actual) {
        assertThat(actual)
            .as("Verify Household relationships")
            .satisfies(a -> assertThat(a.getAreaZone()).as("check areaZone").isEqualTo(expected.getAreaZone()));
    }
}
