package com.policemanagement.com.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PatrolLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatrolLogAllPropertiesEquals(PatrolLog expected, PatrolLog actual) {
        assertPatrolLogAutoGeneratedPropertiesEquals(expected, actual);
        assertPatrolLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatrolLogAllUpdatablePropertiesEquals(PatrolLog expected, PatrolLog actual) {
        assertPatrolLogUpdatableFieldsEquals(expected, actual);
        assertPatrolLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatrolLogAutoGeneratedPropertiesEquals(PatrolLog expected, PatrolLog actual) {
        assertThat(actual)
            .as("Verify PatrolLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatrolLogUpdatableFieldsEquals(PatrolLog expected, PatrolLog actual) {
        assertThat(actual)
            .as("Verify PatrolLog relevant properties")
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getTarget()).as("check target").isEqualTo(expected.getTarget()))
            .satisfies(a -> assertThat(a.getDetails()).as("check details").isEqualTo(expected.getDetails()))
            .satisfies(a -> assertThat(a.getOfficerName()).as("check officerName").isEqualTo(expected.getOfficerName()))
            .satisfies(a -> assertThat(a.getBadgeNumber()).as("check badgeNumber").isEqualTo(expected.getBadgeNumber()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatrolLogUpdatableRelationshipsEquals(PatrolLog expected, PatrolLog actual) {
        // empty method
    }
}
