package com.policemanagement.com.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResidentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResidentAllPropertiesEquals(Resident expected, Resident actual) {
        assertResidentAutoGeneratedPropertiesEquals(expected, actual);
        assertResidentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResidentAllUpdatablePropertiesEquals(Resident expected, Resident actual) {
        assertResidentUpdatableFieldsEquals(expected, actual);
        assertResidentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResidentAutoGeneratedPropertiesEquals(Resident expected, Resident actual) {
        assertThat(actual)
            .as("Verify Resident auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResidentUpdatableFieldsEquals(Resident expected, Resident actual) {
        assertThat(actual)
            .as("Verify Resident relevant properties")
            .satisfies(a -> assertThat(a.getFullName()).as("check fullName").isEqualTo(expected.getFullName()))
            .satisfies(a -> assertThat(a.getIdCardNumber()).as("check idCardNumber").isEqualTo(expected.getIdCardNumber()))
            .satisfies(a -> assertThat(a.getBirthYear()).as("check birthYear").isEqualTo(expected.getBirthYear()))
            .satisfies(a -> assertThat(a.getGender()).as("check gender").isEqualTo(expected.getGender()))
            .satisfies(a -> assertThat(a.getRelationship()).as("check relationship").isEqualTo(expected.getRelationship()))
            .satisfies(a -> assertThat(a.getResidenceType()).as("check residenceType").isEqualTo(expected.getResidenceType()))
            .satisfies(a ->
                assertThat(a.getTemporaryRegisteredAt()).as("check temporaryRegisteredAt").isEqualTo(expected.getTemporaryRegisteredAt())
            )
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResidentUpdatableRelationshipsEquals(Resident expected, Resident actual) {
        assertThat(actual)
            .as("Verify Resident relationships")
            .satisfies(a -> assertThat(a.getHousehold()).as("check household").isEqualTo(expected.getHousehold()));
    }
}
