package com.policemanagement.com.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SecurityAlertAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecurityAlertAllPropertiesEquals(SecurityAlert expected, SecurityAlert actual) {
        assertSecurityAlertAutoGeneratedPropertiesEquals(expected, actual);
        assertSecurityAlertAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecurityAlertAllUpdatablePropertiesEquals(SecurityAlert expected, SecurityAlert actual) {
        assertSecurityAlertUpdatableFieldsEquals(expected, actual);
        assertSecurityAlertUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecurityAlertAutoGeneratedPropertiesEquals(SecurityAlert expected, SecurityAlert actual) {
        assertThat(actual)
            .as("Verify SecurityAlert auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecurityAlertUpdatableFieldsEquals(SecurityAlert expected, SecurityAlert actual) {
        assertThat(actual)
            .as("Verify SecurityAlert relevant properties")
            .satisfies(a -> assertThat(a.getAlertType()).as("check alertType").isEqualTo(expected.getAlertType()))
            .satisfies(a -> assertThat(a.getSeverity()).as("check severity").isEqualTo(expected.getSeverity()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()))
            .satisfies(a -> assertThat(a.getIsResolved()).as("check isResolved").isEqualTo(expected.getIsResolved()))
            .satisfies(a -> assertThat(a.getReportedAt()).as("check reportedAt").isEqualTo(expected.getReportedAt()))
            .satisfies(a -> assertThat(a.getResolvedAt()).as("check resolvedAt").isEqualTo(expected.getResolvedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecurityAlertUpdatableRelationshipsEquals(SecurityAlert expected, SecurityAlert actual) {
        // empty method
    }
}
